server:
  servlet:
    context-path: /products
  port: 8091

spring:
  application:
    name: product-service
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        enabled: true
        register-enabled: true
        ip-type: IPV4
        namespace: 4bf80b0c-03ae-4d78-9a9a-7195df8ee4c5
        cluster-name: sky-cluster
        group: dev

    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
        heartbeat-interval-ms: 10




feign:
  sentinel:
    enabled: true
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        read-timeout: 2000
        connect-timeout: 3000
        logger-level: basic
  compression:
    response:
      enabled: true



ribbon:
  eager-load:
    clients: user-service
    enabled: true # 开始饥饿加载，防止第一次调用超时
