server:
  servlet:
    context-path: /products
  port: 8091

spring:
  application:
    name: product-service
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719